#!/usr/bin/env bash
# Build or smoke-check an ML Glossary style Sphinx documentation tree.
#
# This helper is bundled with the runtime skill and does not assume the original
# repository checkout exists. Use --self-test for a tiny generated project, or
# pass --docs-dir/--build-dir when maintaining a user-provided checkout.
#
# Examples:
#   bash scripts/build_docs.sh --self-test
#   bash scripts/build_docs.sh --docs-dir CHECKOUT_DOCS_DIR --build-dir BUILD_OUTPUT_DIR

set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: build_docs.sh [--self-test] [--docs-dir DIR --build-dir DIR] [--builder html] [--strict]

Options:
  --self-test       Build a tiny temporary RST project generated by this script.
  --docs-dir DIR    Sphinx source directory from a user-provided checkout.
  --build-dir DIR   Sphinx output directory. Required unless --self-test is used.
  --builder NAME    Sphinx builder to use (default: html).
  --strict          Pass -W so Sphinx warnings fail the build.
  --help            Show this help.

The script checks Sphinx availability and runs sphinx-build. It never assumes
that the source checkout used to generate the skill still exists.
USAGE
}

SELF_TEST=0
DOCS_DIR=""
BUILD_DIR=""
BUILDER="html"
STRICT=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --self-test)
      SELF_TEST=1
      shift
      ;;
    --docs-dir)
      DOCS_DIR="${2:-}"
      shift 2
      ;;
    --build-dir)
      BUILD_DIR="${2:-}"
      shift 2
      ;;
    --builder)
      BUILDER="${2:-}"
      shift 2
      ;;
    --strict)
      STRICT=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! command -v sphinx-build >/dev/null 2>&1; then
  echo "ERROR: sphinx-build is not on PATH." >&2
  echo "Install docs dependencies such as: python -m pip install sphinx sphinx-rtd-theme recommonmark" >&2
  exit 127
fi

TMP_ROOT=""
cleanup() {
  if [[ -n "$TMP_ROOT" && -d "$TMP_ROOT" ]]; then
    rm -rf "$TMP_ROOT"
  fi
}
trap cleanup EXIT

if [[ "$SELF_TEST" -eq 1 ]]; then
  TMP_ROOT="$(mktemp -d)"
  DOCS_DIR="$TMP_ROOT/src"
  BUILD_DIR="$TMP_ROOT/build"
  mkdir -p "$DOCS_DIR"
  cat > "$DOCS_DIR/conf.py" <<'PY'
extensions = ['sphinx.ext.mathjax']
master_doc = 'index'
project = 'ML Glossary self-test'
html_theme = 'alabaster'
exclude_patterns = ['_build']
PY
  cat > "$DOCS_DIR/index.rst" <<'RST'
=====================
ML Glossary Self-Test
=====================

This tiny page verifies that Sphinx can render headings, math, and a short glossary-style entry.

.. math::

   y = mx + b

Gradient Descent
  Iteratively updates parameters in the direction opposite the gradient to reduce a cost function.
RST
else
  if [[ -z "$DOCS_DIR" || -z "$BUILD_DIR" ]]; then
    echo "ERROR: provide --self-test or both --docs-dir and --build-dir." >&2
    usage >&2
    exit 2
  fi
fi

if [[ ! -d "$DOCS_DIR" ]]; then
  echo "ERROR: docs directory does not exist: $DOCS_DIR" >&2
  exit 2
fi

mkdir -p "$BUILD_DIR"
ARGS=(-b "$BUILDER")
if [[ "$STRICT" -eq 1 ]]; then
  ARGS=(-W "${ARGS[@]}")
fi

set -x
sphinx-build "${ARGS[@]}" "$DOCS_DIR" "$BUILD_DIR"
set +x

echo "Sphinx build completed: $BUILD_DIR"
