#!/usr/bin/env python3
"""Write a non-executing OWL Workforce configuration skeleton.

The generated file contains placeholders and comments only. It never imports
OWL, contacts a model provider, or embeds a credential.
"""
from __future__ import annotations

import argparse
from pathlib import Path

TEMPLATE = '''"""OWL Workforce skeleton generated by the repo skill.

Fill in a provider-backed CAMEL model and tool list after validating a protected
configuration file. This file intentionally does not execute a task.
"""

from camel.agents import ChatAgent
from camel.models import ModelFactory
from camel.societies import Workforce

PROVIDER = {provider!r}


def build_workforce() -> Workforce:
    # Replace this marker with a provider-specific ModelFactory.create call.
    model = None  # configure a tool-capable model; do not paste a secret here
    if model is None:
        raise RuntimeError("Configure a provider model before executing")
    coordinator = ChatAgent("Decompose and assign tasks.", model=model)
    planner = ChatAgent("Plan the next worker action.", model=model)
    worker = ChatAgent("Execute only the assigned specialist work.", model=model, tools=[])
    workforce = Workforce("Workforce", task_agent=planner, coordinator_agent=coordinator)
    workforce.add_single_agent_worker("Specialist worker", worker=worker)
    return workforce


if __name__ == "__main__":
    raise SystemExit("Skeleton only: configure and review the model/tools before running")
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--provider", choices=["openai", "anthropic", "qwen", "deepseek", "gemini", "groq", "openai-compatible"], required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(TEMPLATE.format(provider=args.provider), encoding="utf-8")
    print(f"wrote non-executing Workforce skeleton: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
