#!/usr/bin/env python3
"""Build a self-contained MMYOLO image inference command.

This helper mirrors MMYOLO image-demo-style options, but it never imports
MMYOLO, loads a model, downloads data, or runs inference. It only validates
builder-level arguments and emits either a shell heredoc or a Python script that
uses installed MMYOLO/MMDetection APIs.
"""

from __future__ import annotations

import argparse
import shlex
import sys
import textwrap
from pathlib import Path
from typing import Iterable


IMAGE_EXTENSIONS = (
    ".jpg",
    ".jpeg",
    ".png",
    ".ppm",
    ".bmp",
    ".pgm",
    ".tif",
    ".tiff",
    ".webp",
)


def is_url(value: str) -> bool:
    return value.startswith(("http:/", "https:/"))


def validate_existing_inputs(args: argparse.Namespace) -> None:
    """Perform optional local path validation without running inference."""
    config = Path(args.config)
    checkpoint = Path(args.checkpoint)
    if not config.is_file():
        raise FileNotFoundError(f"Config file does not exist: {args.config}")
    if not checkpoint.is_file():
        raise FileNotFoundError(
            f"Checkpoint file does not exist: {args.checkpoint}")

    if is_url(args.img):
        return
    source = Path(args.img)
    if source.is_dir():
        found = any(p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
                    for p in source.rglob("*"))
        if not found:
            raise FileNotFoundError(
                f"Directory has no supported image files: {args.img}")
    elif not source.is_file() or source.suffix.lower() not in IMAGE_EXTENSIONS:
        raise FileNotFoundError(
            "Image input must be a supported image file, image directory, "
            f"or URL: {args.img}")


def py_literal(value: object) -> str:
    """Return a deterministic Python literal for emitted scripts."""
    return repr(value)


def build_python_script(args: argparse.Namespace) -> str:
    class_names = None if args.class_name is None else list(args.class_name)
    template = r'''
        # Generated by mmyolo_infer_image_command.py.
        # Run this script in an environment where MMYOLO, MMDetection, MMCV,
        # MMEngine, and PyTorch are installed. It does not require MMYOLO
        # source-checkout demo scripts.
        import os
        from pathlib import Path

        import mmcv
        from mmdet.apis import inference_detector, init_detector
        from mmengine.config import Config, ConfigDict
        from mmengine.utils import ProgressBar

        from mmyolo.registry import VISUALIZERS
        from mmyolo.utils import register_all_modules, switch_to_deploy
        from mmyolo.utils.labelme_utils import LabelmeFormat
        from mmyolo.utils.misc import get_file_list

        IMG = @@IMG@@
        CONFIG = @@CONFIG@@
        CHECKPOINT = @@CHECKPOINT@@
        OUT_DIR = @@OUT_DIR@@
        DEVICE = @@DEVICE@@
        SHOW = @@SHOW@@
        DEPLOY = @@DEPLOY@@
        TTA = @@TTA@@
        SCORE_THR = @@SCORE_THR@@
        CLASS_NAMES = @@CLASS_NAMES@@
        TO_LABELME = @@TO_LABELME@@


        def load_config(config_path):
            cfg = Config.fromfile(config_path)
            try:
                if "init_cfg" in cfg.model.backbone:
                    cfg.model.backbone.init_cfg = None
            except Exception:
                pass

            if TTA:
                if "tta_model" not in cfg or "tta_pipeline" not in cfg:
                    raise RuntimeError(
                        "TTA requested, but config is missing tta_model "
                        "or tta_pipeline.")
                cfg.model = ConfigDict(**cfg.tta_model, module=cfg.model)
                test_data_cfg = cfg.test_dataloader.dataset
                while "dataset" in test_data_cfg:
                    test_data_cfg = test_data_cfg["dataset"]
                if "batch_shapes_cfg" in test_data_cfg:
                    test_data_cfg.batch_shapes_cfg = None
                test_data_cfg.pipeline = cfg.tta_pipeline
            return cfg


        def validate_runtime_args():
            if TO_LABELME and SHOW:
                raise RuntimeError(
                    "`--to-labelme` and `--show` cannot be used together.")
            if not 0.0 <= SCORE_THR <= 1.0:
                raise ValueError("score threshold should be between 0 and 1")
            if not Path(CONFIG).is_file():
                raise FileNotFoundError(f"Config file does not exist: {CONFIG}")
            if not Path(CHECKPOINT).is_file():
                raise FileNotFoundError(
                    f"Checkpoint file does not exist: {CHECKPOINT}")


        def main():
            validate_runtime_args()
            register_all_modules(init_default_scope=True)
            cfg = load_config(CONFIG)
            model = init_detector(
                cfg, CHECKPOINT, device=DEVICE, cfg_options={})
            if DEPLOY:
                switch_to_deploy(model)

            if not SHOW:
                Path(OUT_DIR).mkdir(parents=True, exist_ok=True)

            visualizer = VISUALIZERS.build(model.cfg.visualizer)
            visualizer.dataset_meta = model.dataset_meta

            files, source_type = get_file_list(IMG)
            if not files:
                raise FileNotFoundError(
                    "No supported image inputs were found for: " + IMG)

            dataset_classes = tuple(model.dataset_meta.get("classes", ()))
            if TO_LABELME and not dataset_classes:
                raise RuntimeError(
                    "LabelMe export requires model.dataset_meta['classes'].")
            if CLASS_NAMES is not None:
                if not dataset_classes:
                    raise RuntimeError(
                        "Class filtering requires model.dataset_meta['classes'].")
                unknown = [name for name in CLASS_NAMES
                           if name not in dataset_classes]
                if unknown:
                    raise RuntimeError(
                        "Unknown class names: " + repr(unknown) +
                        "; available classes: " + repr(dataset_classes))

            labelme_writer = LabelmeFormat(classes=dataset_classes)
            progress_bar = ProgressBar(len(files))

            for file in files:
                result = inference_detector(model, file)
                raw_img = mmcv.imread(file)
                if raw_img is None:
                    raise RuntimeError("Could not read image: " + str(file))
                img = mmcv.imconvert(raw_img, "bgr", "rgb")

                if source_type.get("is_dir"):
                    filename = os.path.relpath(file, IMG)
                    filename = filename.replace(os.sep, "_").replace("/", "_")
                else:
                    filename = os.path.basename(file)
                out_file = None if SHOW else str(Path(OUT_DIR) / filename)

                pred_instances = result.pred_instances[
                    result.pred_instances.scores > SCORE_THR]

                if TO_LABELME:
                    label_file = str(Path(out_file).with_suffix(".json"))
                    labelme_writer(
                        pred_instances,
                        result.metainfo,
                        label_file,
                        CLASS_NAMES,
                    )
                else:
                    visualizer.add_datasample(
                        filename,
                        img,
                        data_sample=result,
                        draw_gt=False,
                        show=SHOW,
                        wait_time=0,
                        out_file=out_file,
                        pred_score_thr=SCORE_THR,
                    )
                progress_bar.update()

            if not SHOW and not TO_LABELME:
                print("Results have been saved at " +
                      str(Path(OUT_DIR).resolve()))
            elif TO_LABELME:
                print("LabelMe files have been saved in " +
                      str(Path(OUT_DIR).resolve()))


        if __name__ == "__main__":
            main()
    '''
    replacements = {
        "@@IMG@@": py_literal(args.img),
        "@@CONFIG@@": py_literal(args.config),
        "@@CHECKPOINT@@": py_literal(args.checkpoint),
        "@@OUT_DIR@@": py_literal(args.out_dir),
        "@@DEVICE@@": py_literal(args.device),
        "@@SHOW@@": py_literal(bool(args.show)),
        "@@DEPLOY@@": py_literal(bool(args.deploy)),
        "@@TTA@@": py_literal(bool(args.tta)),
        "@@SCORE_THR@@": py_literal(float(args.score_thr)),
        "@@CLASS_NAMES@@": py_literal(class_names),
        "@@TO_LABELME@@": py_literal(bool(args.to_labelme)),
    }
    script = textwrap.dedent(template).strip() + "\n"
    for token, value in replacements.items():
        script = script.replace(token, value)
    return script


def build_shell_command(args: argparse.Namespace) -> str:
    python_script = build_python_script(args)
    return (f"{shlex.quote(args.python)} - <<'PY'\n"
            f"{python_script}"
            "PY\n")


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Emit a self-contained MMYOLO image/folder/URL inference command "
            "using installed APIs. The builder performs no inference."))
    parser.add_argument("img", help="Image path, directory, or URL.")
    parser.add_argument("config", help="MMYOLO config file path.")
    parser.add_argument("checkpoint", help="Checkpoint file path.")
    parser.add_argument(
        "--out-dir", default="./output",
        help="Output directory encoded into the generated command.")
    parser.add_argument(
        "--device", default="cpu",
        help="Device encoded into the generated command. Default is cpu for portability.")
    parser.add_argument(
        "--show", action="store_true",
        help="Generate a command that displays results instead of saving normal visualized images.")
    parser.add_argument(
        "--deploy", action="store_true",
        help="Generate a command that switches compatible PyTorch blocks to deploy mode.")
    parser.add_argument(
        "--tta", action="store_true",
        help="Generate a command that applies config TTA fields before model construction.")
    parser.add_argument(
        "--score-thr", type=float, default=0.3,
        help="Prediction score threshold encoded into the generated command.")
    parser.add_argument(
        "--class-name", nargs="+", type=str,
        help="Class names to validate and pass to LabelMe export.")
    parser.add_argument(
        "--to-labelme", action="store_true",
        help="Generate a command that writes LabelMe JSON files instead of visualized images.")
    parser.add_argument(
        "--emit", choices=("shell", "python"), default="shell",
        help="Emit a shell heredoc command or raw Python source. Default: shell.")
    parser.add_argument(
        "--python", default="python",
        help="Python executable name/path used only when --emit shell.")
    parser.add_argument(
        "--check-paths", action="store_true",
        help="Optionally check local image/config/checkpoint paths before emitting.")
    return parser


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = make_parser()
    args = parser.parse_args(argv)
    if args.show and args.to_labelme:
        parser.error("`--show` and `--to-labelme` cannot be used together")
    if not 0.0 <= args.score_thr <= 1.0:
        parser.error("--score-thr should be between 0 and 1")
    if args.check_paths:
        try:
            validate_existing_inputs(args)
        except Exception as exc:  # argparse-friendly message
            parser.error(str(exc))
    return args


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)
    if args.emit == "python":
        sys.stdout.write(build_python_script(args))
    else:
        sys.stdout.write(build_shell_command(args))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
