#!/usr/bin/env python3
"""Convert a Porcupine binary asset into a C uint8_t array header.

The helper is intentionally checkout-independent: it accepts explicit input,
symbol, and output paths, validates the symbol as a safe C identifier, and
writes a self-contained header fragment suitable for MCU/static embedding.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
from typing import Iterable


_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_C_KEYWORDS = {
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    "_Alignas",
    "_Alignof",
    "_Atomic",
    "_Bool",
    "_Complex",
    "_Generic",
    "_Imaginary",
    "_Noreturn",
    "_Static_assert",
    "_Thread_local",
}


def _validate_symbol(value: str) -> str:
    if not _IDENTIFIER_RE.fullmatch(value):
        raise argparse.ArgumentTypeError(
            "symbol must be a C identifier: [A-Za-z_][A-Za-z0-9_]*"
        )
    if value in _C_KEYWORDS:
        raise argparse.ArgumentTypeError(f"symbol must not be the C keyword {value!r}")
    if value.startswith("__") or (len(value) > 1 and value[0] == "_" and value[1].isupper()):
        raise argparse.ArgumentTypeError(
            "symbol must not use reserved implementation identifiers such as __name or _Name"
        )
    return value


def _guard_for(symbol: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9]", "_", symbol).upper()
    return f"PORCUPINE_GENERATED_{normalized}_H"


def _format_bytes(data: bytes, *, per_line: int = 12) -> Iterable[str]:
    for offset in range(0, len(data), per_line):
        chunk = data[offset : offset + per_line]
        suffix = "," if offset + per_line < len(data) else ""
        yield "    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + suffix


def _render_header(data: bytes, symbol: str) -> str:
    guard = _guard_for(symbol)
    rows = "\n".join(_format_bytes(data))
    return f"""/* Generated by porcupine_binary_to_c_array.py. */
#ifndef {guard}
#define {guard}

#include <stdint.h>

#if defined(_MSC_VER)
#define PORCUPINE_GENERATED_ALIGN_16_PRE __declspec(align(16))
#define PORCUPINE_GENERATED_ALIGN_16_POST
#else
#define PORCUPINE_GENERATED_ALIGN_16_PRE
#define PORCUPINE_GENERATED_ALIGN_16_POST __attribute__((aligned(16)))
#endif

PORCUPINE_GENERATED_ALIGN_16_PRE static const uint8_t {symbol}[] PORCUPINE_GENERATED_ALIGN_16_POST = {{
{rows}
}};

static const int32_t {symbol}_SIZE = (int32_t) sizeof({symbol});

#undef PORCUPINE_GENERATED_ALIGN_16_PRE
#undef PORCUPINE_GENERATED_ALIGN_16_POST

#endif /* {guard} */
"""


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Convert a Porcupine .ppn/.pv or other binary asset to a C header "
            "containing a validated uint8_t array and <symbol>_SIZE."
        )
    )
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Path to the binary asset to convert.",
    )
    parser.add_argument(
        "--symbol",
        required=True,
        type=_validate_symbol,
        help="C array symbol to emit, e.g. DEFAULT_KEYWORD_ARRAY.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Header path to write. Parent directories are created if needed.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    input_path: Path = args.input
    output_path: Path = args.output

    if not input_path.exists():
        parser.error(f"--input does not exist: {input_path}")
    if not input_path.is_file():
        parser.error(f"--input is not a regular file: {input_path}")
    if output_path.exists() and output_path.is_dir():
        parser.error(f"--output is a directory: {output_path}")
    if input_path.resolve() == output_path.resolve():
        parser.error("--output must not overwrite --input")

    data = input_path.read_bytes()
    if not data:
        parser.error(f"--input is empty: {input_path}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_render_header(data, args.symbol), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
