#!/usr/bin/env python3
"""Build the VITS monotonic-alignment extension into the importable layout.

Prereqs:
- Run from any working directory with `--repo-root` pointing at a VITS checkout.
- Requires Cython, numpy, and a compiler toolchain.
- This helper fixes the source repo's build-layout mismatch by copying the
  compiled extension into `monotonic_align/monotonic_align/`.

Example:
  python scripts/build_monotonic_align.py --repo-root /path/to/vits
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from importlib.machinery import EXTENSION_SUFFIXES
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the monotonic_align extension.")
    parser.add_argument("--repo-root", required=True, help="Path to the VITS checkout.")
    parser.add_argument(
        "--validate",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Import the compiled extension after copying it into place.",
    )
    return parser.parse_args()


def find_built_extension(build_dir: Path) -> Path:
    suffixes = EXTENSION_SUFFIXES or [".so"]
    candidates = []
    for suffix in suffixes:
        candidates.extend(build_dir.rglob(f"core*{suffix}"))
    candidates = [path for path in candidates if path.is_file()]
    if not candidates:
        raise FileNotFoundError(f"No compiled extension found under {build_dir}")
    candidates.sort(key=lambda p: (len(p.parts), str(p)))
    return candidates[-1]


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).expanduser().resolve()
    package_dir = repo_root / "monotonic_align"
    setup_py = package_dir / "setup.py"
    if not setup_py.exists():
        raise FileNotFoundError(f"Expected {setup_py}")

    nested_dir = package_dir / "monotonic_align"
    nested_dir.mkdir(parents=True, exist_ok=True)
    init_file = nested_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# Generated by build_monotonic_align.py\n", encoding="utf-8")

    print(f"Building extension in {package_dir}")
    subprocess.run([sys.executable, "setup.py", "build_ext"], cwd=package_dir, check=True)

    build_dir = package_dir / "build"
    built = find_built_extension(build_dir)
    target = nested_dir / built.name
    shutil.copy2(built, target)
    print(f"Copied {built} -> {target}")

    if args.validate:
        check = [
            sys.executable,
            "-I",
            "-c",
            "import sys; from pathlib import Path; sys.path.insert(0, str(Path(r'%s'))); "
            "import monotonic_align; from monotonic_align.monotonic_align.core import maximum_path_c; "
            "print('monotonic_align ok', maximum_path_c)" % repo_root,
        ]
        subprocess.run(check, check=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
