#!/usr/bin/env python3
"""Render TensorFlowOnSpark Spark ML pipeline skeletons.

This helper only writes code templates. It never trains a model, loads a SavedModel, or submits Spark jobs.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from textwrap import dedent

PLACEHOLDER_INPUT = [("<df_column>", "<input_tensor>")]
PLACEHOLDER_OUTPUT = [("<output_tensor>", "<df_column>")]


def parse_mapping_entries(items, *, mode):
    mapping = []
    seen = set()
    for raw in items:
        if ":" not in raw:
            raise ValueError(f"{mode} mappings must use COL:TENSOR syntax")
        left, right = (part.strip() for part in raw.split(":", 1))
        if not left or not right:
            raise ValueError(f"{mode} mappings must use non-empty COL:TENSOR pairs")
        if left in seen:
            raise ValueError(f"duplicate {mode} mapping key: {left}")
        seen.add(left)
        mapping.append((left, right))
    return sorted(mapping)


def render_mapping_constant(name, mapping, placeholder):
    rows = mapping if mapping else placeholder
    body = "\n".join(f"    {left!r}: {right!r}," for left, right in rows)
    return f"{name} = {{\n{body}\n}}"


def render_header():
    return dedent('''\
        #!/usr/bin/env python3
        """TensorFlowOnSpark Spark ML pipeline skeleton.

        Generated by scripts/render_pipeline_template.py.
        Fill in the TODO blocks before running.
        """

        from __future__ import annotations

        import argparse
        from pyspark.sql import SparkSession
        from tensorflowonspark import TFNode, compat
        from tensorflowonspark.pipeline import TFEstimator, TFModel
        ''').rstrip()


TRAIN_BLOCK = dedent('''\
    def train_fn(args, ctx):
        """TODO: implement the distributed TensorFlow training loop."""
        # Example pattern:
        # tf_feed = TFNode.DataFeed(ctx.mgr, input_mapping=args.input_mapping)
        # while not tf_feed.should_stop():
        #     batch = tf_feed.next_batch(args.batch_size)
        #     ...
        # Export on the chief node only when you need a SavedModel.
        raise NotImplementedError("Fill in the training loop.")


    def load_training_df(spark, args):
        """TODO: load the training DataFrame."""
        raise NotImplementedError("Fill in your training DataFrame loader.")


    def build_estimator(args):
        estimator = TFEstimator(train_fn, args)
        estimator = estimator.setInputMapping(INPUT_MAPPING)
        estimator = estimator.setClusterSize(args.cluster_size)
        estimator = estimator.setBatchSize(args.batch_size)
        estimator = estimator.setEpochs(args.epochs)
        estimator = estimator.setModelDir(args.model_dir)
        estimator = estimator.setExportDir(args.export_dir)
        estimator = estimator.setGraceSecs(args.grace_secs)
        return estimator
''').rstrip()


INFERENCE_BLOCK = dedent('''\
    def load_inference_df(spark, args):
        """TODO: load the inference DataFrame."""
        raise NotImplementedError("Fill in your inference DataFrame loader.")


    def build_model(args):
        model = TFModel(args)
        model = model.setInputMapping(INPUT_MAPPING)
        model = model.setOutputMapping(OUTPUT_MAPPING)
        model = model.setBatchSize(args.batch_size)
        if getattr(args, "model_dir", None):
            model = model.setModelDir(args.model_dir)
        if getattr(args, "export_dir", None):
            model = model.setExportDir(args.export_dir)
        if getattr(args, "tag_set", None):
            model = model.setTagSet(args.tag_set)
        if getattr(args, "signature_def_key", None):
            model = model.setSignatureDefKey(args.signature_def_key)
        return model
''').rstrip()


def render(mode, input_mapping, output_mapping):
    parts = [render_header(), "# Input mapping keys are Spark DataFrame columns; values are TensorFlow input tensors."]
    parts.append(render_mapping_constant("INPUT_MAPPING", input_mapping, PLACEHOLDER_INPUT))

    if mode in {"train", "both"}:
        parts.append(TRAIN_BLOCK)

    if mode in {"inference", "both"}:
        parts.append("# Output mapping keys are TensorFlow output tensors; values are Spark DataFrame columns.")
        parts.append(render_mapping_constant("OUTPUT_MAPPING", output_mapping, PLACEHOLDER_OUTPUT))
        parts.append(INFERENCE_BLOCK)

    return "\n\n".join(parts).rstrip() + "\n"


def build_arg_parser():
    parser = argparse.ArgumentParser(description="Render a TensorFlowOnSpark Spark ML pipeline skeleton.")
    parser.add_argument("--mode", choices=["train", "inference", "both"], default="both", help="Which skeleton sections to render.")
    parser.add_argument("--input-mapping", action="append", default=[], metavar="DF_COL:TENSOR", help="Input mapping entry for the rendered skeleton.")
    parser.add_argument("--output-mapping", action="append", default=[], metavar="TENSOR:DF_COL", help="Output mapping entry for the rendered skeleton.")
    parser.add_argument("--output", default="-", help="Write the rendered skeleton to this path, or '-' for stdout.")
    return parser


def main(argv=None):
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    input_mapping = parse_mapping_entries(args.input_mapping, mode="input")
    output_mapping = parse_mapping_entries(args.output_mapping, mode="output")
    rendered = render(args.mode, input_mapping, output_mapping)
    if args.output == "-":
        print(rendered, end="")
    else:
        path = Path(args.output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
