#!/usr/bin/env python3
"""
Analyze MMDeploy SDK profiler text output.

Purpose:
    Read an SDK profiler file containing a pipeline graph, a `----` separator,
    and start/end event lines, then print per-node timing statistics similar to
    MMDeploy's upstream analyzer.

Prerequisites:
    Python 3.8+ and a text profile generated by MMDeploy SDK profiler APIs. This
    adapted copy is read-only and uses only the Python standard library.

Example:
    python scripts/sdk_analyze.py profiler_data.txt

Input format:
    <node-name> <node-address> [child-address ...]
    ...
    ----
    <node-address> <kind> <call-index> <timestamp>
    ...

    `kind` is 0 for start and nonzero for finish. Durations are reported in
    milliseconds, matching the original analyzer's timestamp / 1000 convention.
"""

from __future__ import annotations

import argparse
import statistics
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Set, Tuple, Union

NumberOrDash = Union[float, str]


@dataclass
class Graph:
    addr2name: Dict[str, str] = field(default_factory=dict)
    addr2id: Dict[str, int] = field(default_factory=dict)
    id2addr: Dict[int, str] = field(default_factory=dict)
    children: Dict[str, List[str]] = field(default_factory=dict)
    parent: Dict[str, str] = field(default_factory=dict)


@dataclass
class Stats:
    occupy: Dict[int, int]
    usage: Dict[int, int]
    calls: Dict[int, int]
    times: Dict[int, List[int]]
    used_ids: Set[int]
    used_addrs: Set[str]
    first_id: int


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Analyze an MMDeploy SDK profiler text file.')
    parser.add_argument('profile_file', help='path to SDK profiler text file')
    return parser.parse_args(argv)


def split_profile(text: str) -> Tuple[List[str], List[str]]:
    graph_lines: List[str] = []
    event_lines: List[str] = []
    in_events = False
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line == '----':
            if in_events:
                raise ValueError('profile contains more than one ---- separator')
            in_events = True
            continue
        if in_events:
            event_lines.append(line)
        else:
            graph_lines.append(line)
    if not in_events:
        raise ValueError('missing ---- separator between graph and events')
    if not graph_lines:
        raise ValueError('empty graph section')
    if not event_lines:
        raise ValueError('empty event section')
    return graph_lines, event_lines


def parse_graph(lines: Iterable[str]) -> Graph:
    graph = Graph()
    for index, line in enumerate(lines):
        parts = line.split()
        if len(parts) < 2:
            raise ValueError(f'malformed graph line {index + 1}: {line!r}')
        name, addr = parts[:2]
        if addr in graph.addr2name:
            raise ValueError(f'duplicate node address in graph: {addr}')
        graph.addr2name[addr] = name
        graph.addr2id[addr] = index
        graph.id2addr[index] = addr
        graph.children[addr] = list(parts[2:])
    for addr, child_addrs in graph.children.items():
        for child in child_addrs:
            if child not in graph.addr2name:
                raise ValueError(f'graph references unknown child address {child!r}')
            if child in graph.parent:
                raise ValueError(f'graph child {child!r} has multiple parents')
            graph.parent[child] = addr
    return graph


def percentile_from_sorted(values: Sequence[int], fraction: float) -> int:
    if not values:
        return 0
    index = min(int(len(values) * fraction), len(values) - 1)
    return values[index]


def compute_stats(graph: Graph, lines: Iterable[str]) -> Stats:
    node_count = len(graph.addr2id)
    active = {i: 0 for i in range(node_count)}
    calls = {i: 0 for i in range(node_count)}
    occupy = {i: 0 for i in range(node_count)}
    usage = {i: 0 for i in range(node_count)}
    times = {i: [] for i in range(node_count)}
    starts: Dict[Tuple[int, int], int] = {}
    used_ids: Set[int] = set()
    used_addrs: Set[str] = set()
    now = 0
    first_id: int | None = None

    for line_number, line in enumerate(lines, start=1):
        parts = line.split()
        if len(parts) != 4:
            raise ValueError(f'malformed event line {line_number}: {line!r}')
        addr = parts[0]
        if addr not in graph.addr2id:
            raise ValueError(f'event line {line_number} references unknown address {addr!r}')
        try:
            kind, call_index, timestamp = map(int, parts[1:])
        except ValueError as exc:
            raise ValueError(f'event line {line_number} has non-integer fields: {line!r}') from exc

        node_id = graph.addr2id[addr]
        if first_id is None:
            first_id = node_id
        used_addrs.add(addr)
        used_ids.add(node_id)

        if node_id == first_id and kind == 0 and active[node_id] == 0:
            now = timestamp

        delta = timestamp - now
        if delta < 0:
            raise ValueError(f'event line {line_number} timestamp goes backwards')
        now = timestamp

        for active_id, active_count in active.items():
            if active_count > 0:
                occupy[active_id] += delta
                usage[active_id] += delta * active_count

        key = (node_id, call_index)
        if kind == 0:
            if key in starts:
                raise ValueError(f'event line {line_number} duplicates active start {key}')
            starts[key] = timestamp
            active[node_id] += 1
            calls[node_id] += 1
        else:
            if key not in starts:
                raise ValueError(f'event line {line_number} closes missing start {key}')
            duration = timestamp - starts.pop(key)
            if duration < 0:
                raise ValueError(f'event line {line_number} has negative duration')
            times[node_id].append(duration)
            active[node_id] -= 1
            if active[node_id] < 0:
                raise ValueError(f'event line {line_number} over-closes node {addr!r}')

    if first_id is None:
        raise ValueError('no events found')
    if starts:
        raise ValueError(f'unclosed profiler events remain: {sorted(starts)[:5]}')
    return Stats(occupy, usage, calls, times, used_ids, used_addrs, first_id)


def nested_name(addr: str, graph: Graph, used_addrs: Set[str], depth: int = 0,
                skip: bool = False, visiting: Set[str] | None = None) -> str:
    if visiting is None:
        visiting = set()
    if addr in visiting:
        return graph.addr2name[addr]
    visiting.add(addr)

    node_name = graph.addr2name[addr] if not skip else ''
    if addr not in graph.parent:
        return ' ' * depth * 4 + node_name
    parent_addr = graph.parent[addr]
    if parent_addr in used_addrs:
        depth += 1
        skip = True
    parent_name = nested_name(parent_addr, graph, used_addrs, depth, skip, visiting)
    if len(parent_name.split()) == 0:
        return parent_name + node_name
    return parent_name + '/' + node_name


def fmt_value(value: NumberOrDash) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, int):
        return str(value)
    return f'{value:.3f}'


def make_rows(graph: Graph, stats: Stats) -> List[List[Union[str, int, float]]]:
    denominator = stats.occupy[stats.first_id]
    rows: List[List[Union[str, int, float]]] = []
    for node_id in sorted(stats.used_ids):
        addr = graph.id2addr[node_id]
        node_times = sorted(stats.times[node_id])
        if not node_times:
            # A node that only has a start event would have failed earlier, but
            # keep this guard for compatibility with sparse profiler outputs.
            mean_ms = p50_ms = p90_ms = 0.0
        else:
            mean_ms = statistics.fmean(node_times) / 1000
            p50_ms = percentile_from_sorted(node_times, 0.5) / 1000
            p90_ms = percentile_from_sorted(node_times, 0.9) / 1000

        if graph.children[addr]:
            occupy_value: NumberOrDash = '-'
            usage_value: NumberOrDash = '-'
        elif denominator > 0:
            occupy_value = stats.occupy[node_id] / denominator
            usage_value = stats.usage[node_id] / denominator
        else:
            occupy_value = 0.0
            usage_value = 0.0

        rows.append([
            nested_name(addr, graph, stats.used_addrs),
            occupy_value,
            usage_value,
            stats.calls[node_id],
            mean_ms,
            p50_ms,
            p90_ms,
        ])
    return rows


def render_table(headers: Sequence[str], rows: Sequence[Sequence[Union[str, int, float]]]) -> str:
    rendered_rows = [[fmt_value(cell) for cell in row] for row in rows]
    widths = [len(header) for header in headers]
    for row in rendered_rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))

    def border(char: str = '-') -> str:
        return '+' + '+'.join(char * (width + 2) for width in widths) + '+'

    def render_row(row: Sequence[str]) -> str:
        cells = [f' {cell:<{widths[i]}} ' for i, cell in enumerate(row)]
        return '|' + '|'.join(cells) + '|'

    lines = [border('-'), render_row(headers), border('=')]
    for row in rendered_rows:
        lines.append(render_row(row))
        lines.append(border('-'))
    return '\n'.join(lines)


def analyze(path: Path) -> str:
    text = path.read_text()
    graph_lines, event_lines = split_profile(text)
    graph = parse_graph(graph_lines)
    stats = compute_stats(graph, event_lines)
    rows = make_rows(graph, stats)
    headers = ['name', 'occupy', 'usage', 'n_call', 't_mean', 't_50%', 't_90%']
    return render_table(headers, rows)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        print(analyze(Path(args.profile_file)))
    except Exception as exc:  # noqa: BLE001 - CLI should print concise errors.
        print(f'error: {exc}', file=sys.stderr)
        return 2
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
