#!/usr/bin/env python3
"""Generate a self-contained LangExtract provider plugin package.

The generator is safe by default: it writes a package scaffold under the current
working directory or --output-dir and does not install packages, call model APIs,
or depend on the original LangExtract source checkout. Use --install-and-test
only in a throwaway environment where mutating installed packages is acceptable.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import subprocess
import sys
import textwrap
from string import Template

_MARKER = ".langextract-provider-plugin-generated"

_PROVIDER_TEMPLATE = Template('''\
"""Provider implementation for $provider_display."""

from __future__ import annotations

from collections.abc import Iterator, Sequence
import os
from typing import Any

from langextract.core import base_model, exceptions, types
from langextract.providers import router
$schema_import


@router.register($patterns_literal, priority=$priority)
class $class_name(base_model.BaseLanguageModel):
    """LangExtract provider for $provider_display.

    Replace the mock inference body with calls to your backend SDK. Keep the
    public infer() shape: one sequence of ScoredOutput objects per prompt.
    """

    def __init__(
        self,
        model_id: str = "$default_model_id",
        api_key: str | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(**kwargs)
        self.model_id = model_id
        self.api_key = api_key or os.environ.get("$env_var")
        self._extra_kwargs = kwargs.copy()
$schema_init
        # TODO: initialize your backend client here. If a required SDK or
        # credential is missing, raise exceptions.InferenceConfigError with a
        # clear installation or configuration hint.

$schema_methods
    def infer(
        self, batch_prompts: Sequence[str], **kwargs: Any
    ) -> Iterator[Sequence[types.ScoredOutput]]:
        """Run inference and yield ranked outputs for each prompt.

        Args:
            batch_prompts: Prompts generated by LangExtract.
            **kwargs: Runtime provider kwargs; these override constructor
                kwargs via merge_kwargs().

        Yields:
            One sequence of ScoredOutput objects per prompt.
        """
        effective_kwargs = self.merge_kwargs(kwargs)
        for prompt in batch_prompts:
$schema_runtime
            output_text = self._mock_generate(prompt, effective_kwargs)
            yield [types.ScoredOutput(score=1.0, output=output_text)]

    def _mock_generate(self, prompt: str, kwargs: dict[str, Any]) -> str:
        """Mock generation used by the scaffold's non-live tests."""
        del kwargs
        if getattr(self, "structured_output", False):
            return '{"extractions": []}'
        return f"Mock response from $class_name for {prompt[:80]}"
''')

_SCHEMA_TEMPLATE = Template('''\
"""Schema implementation for $provider_display."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from langextract.core import data
from langextract.core import schema as core_schema
from langextract.core import types


class $schema_class(core_schema.BaseSchema):
    """Example schema adapter for $provider_display structured output."""

    def __init__(
        self,
        schema_dict: dict[str, Any],
        *,
        raw_output: bool = True,
    ) -> None:
        self._schema_dict = schema_dict
        self._raw_output = raw_output

    @classmethod
    def from_examples(
        cls,
        examples_data: Sequence[data.ExampleData],
        attribute_suffix: str = data.ATTRIBUTE_SUFFIX,
    ) -> $schema_class:
        """Build a provider schema from LangExtract examples."""
        extraction_classes: set[str] = set()
        attribute_keys: set[str] = set()
        for example in examples_data:
            for extraction in example.extractions:
                extraction_classes.add(extraction.extraction_class)
                if extraction.attributes:
                    attribute_keys.update(extraction.attributes)

        extraction_item: dict[str, Any] = {
            "type": "object",
            "properties": {
                "extraction_class": {"type": "string"},
                "extraction_text": {"type": "string"},
                "attributes": {
                    "type": "object",
                    "properties": {
                        key: {"type": "string"} for key in sorted(attribute_keys)
                    },
                },
            },
            "required": ["extraction_class", "extraction_text"],
        }
        if extraction_classes:
            extraction_item["properties"]["extraction_class"]["enum"] = sorted(
                extraction_classes
            )

        schema_dict = {
            "type": "object",
            "properties": {
                "extractions": {"type": "array", "items": extraction_item}
            },
            "required": ["extractions"],
        }
        return cls(schema_dict, raw_output=True)

    @classmethod
    def from_schema_dict(cls, output_schema: types.JsonSchema) -> $schema_class:
        """Opt in to user-authored LangExtract output_schema."""
        return cls(dict(output_schema), raw_output=True)

    def to_provider_config(self) -> dict[str, Any]:
        """Return kwargs consumed by $class_name.__init__ and infer()."""
        return {
            "response_schema": self._schema_dict,
            "structured_output": True,
        }

    @property
    def requires_raw_output(self) -> bool:
        """Whether the provider emits raw JSON/YAML without Markdown fences."""
        return self._raw_output

    @property
    def schema_dict(self) -> dict[str, Any]:
        """Expose the underlying schema for diagnostics and tests."""
        return self._schema_dict
''')

_INIT_TEMPLATE = Template('''\
"""LangExtract provider plugin for $provider_display."""

from $module_name.provider import $class_name

__all__ = ["$class_name"]
__version__ = "0.1.0"
''')

_TEST_TEMPLATE = Template('''\
#!/usr/bin/env python3
"""Non-live smoke tests for the $provider_display LangExtract provider."""

from __future__ import annotations

import re

import langextract as lx
from langextract import data, factory
from langextract.providers import router

# Importing the package is useful when running from a source tree without an
# editable install. After pip installation, load_plugins_once() discovers the
# same provider through the entry point.
import $module_name  # noqa: F401

PROVIDER_CLASS_NAME = "$class_name"
MODEL_ID = "$default_model_id"
PATTERNS = $patterns_list


def _example_model_id(pattern: str) -> str:
    base = re.sub(r"^\\^", "", pattern)
    match = re.match(r"[A-Za-z0-9._:/-]+", base)
    prefix = match.group(0) if match else "model"
    return f"{prefix}-smoke"


def main() -> None:
    lx.providers.load_plugins_once()

    model_id = _example_model_id(PATTERNS[0]) if PATTERNS else MODEL_ID
    provider_cls = router.resolve(model_id)
    assert provider_cls.__name__ == PROVIDER_CLASS_NAME, (
        f"Expected {PROVIDER_CLASS_NAME}, got {provider_cls.__name__}"
    )

    model = factory.create_model(
        factory.ModelConfig(model_id=model_id, provider=PROVIDER_CLASS_NAME)
    )
    outputs = list(model.infer(["prompt one", "prompt two"]))
    assert len(outputs) == 2, outputs
    assert outputs[0] and outputs[0][0].output, outputs
    assert outputs[0][0].score == 1.0, outputs
    print(f"OK: resolved and ran {type(model).__name__}")

$schema_test

if __name__ == "__main__":
    main()
''')

_README_TEMPLATE = Template('''\
# LangExtract $provider_display Provider

A scaffold for a LangExtract provider plugin. Replace mock inference with your
backend SDK calls, list your actual dependency package, and document supported
model IDs before publishing.

## Install for development

```bash
python -m pip install -e .
```

## Entry point

`pyproject.toml` registers this plugin in the `langextract.providers` group:

```toml
[project.entry-points."langextract.providers"]
$entry_point = "$module_name:$class_name"
```

## Supported model IDs

The generated provider registers these regex patterns:

$patterns_markdown

Use narrow patterns when possible. If you intentionally share a built-in pattern,
ask users to disambiguate with `factory.ModelConfig(provider="$class_name")` or
set an explicit router priority.

## Non-live validation

```bash
python test_plugin.py
```

The generated test checks plugin import, router resolution, factory construction,
infer() output shape, and schema lifecycle when schema support is enabled. It
does not call a live model API.

## Usage sketch

```python
import langextract as lx

config = lx.factory.ModelConfig(
    model_id="$default_model_id",
    provider="$class_name",
    provider_kwargs={
        # "api_key": "...",
        # Add provider-specific kwargs here.
    },
)
model = lx.factory.create_model(config)
```

## Implementation notes

- Implement `infer()` so it yields one sequence of `ScoredOutput` objects per
  prompt.
- Raise `InferenceConfigError` for missing SDKs, credentials, endpoints, or
  invalid model IDs.
- Keep live smoke tests optional and credential-gated.
- If schema support is enabled, keep `requires_raw_output` consistent with the
  actual wire output and clear schema state in `apply_schema(None)`.
''')

_PYPROJECT_TEMPLATE = Template('''\
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "$distribution_name"
version = "0.1.0"
description = "LangExtract provider plugin for $provider_display"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
dependencies = [
    "langextract>=1.0.0",
    # Add your provider SDK dependency here, for example: "your-sdk>=1.0".
]

[project.entry-points."langextract.providers"]
$entry_point = "$module_name:$class_name"

[tool.setuptools.packages.find]
where = ["."]
include = ["$module_name*"]
''')

_GITIGNORE = '''\
# Python
__pycache__/
*.py[cod]
*.so

# Packaging
build/
dist/
*.egg-info/
.eggs/
*.egg

# Test and coverage outputs
.pytest_cache/
.coverage
htmlcov/

# Local secrets and logs
*.secret
*.log
'''

_LICENSE = '''\
Apache License 2.0 placeholder

Replace this file with your chosen license text before distribution.
'''


def _provider_base_name(raw: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", raw)
    if not words:
        raise ValueError("provider_name must contain at least one letter or digit")
    base = "".join(word[:1].upper() + word[1:] for word in words)
    if not base[0].isalpha():
        base = "Provider" + base
    return base


def _default_suffix(provider_base: str) -> str:
    suffix = re.sub(r"[^A-Za-z0-9]+", "", provider_base).lower()
    if suffix.endswith("languagemodel"):
        suffix = suffix[: -len("languagemodel")]
    return suffix or "provider"


def _normalize_suffix(raw: str) -> str:
    suffix = re.sub(r"[^A-Za-z0-9]+", "-", raw).strip("-").lower()
    if not suffix:
        raise ValueError("package name must contain at least one letter or digit")
    if not re.match(r"^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$", suffix):
        raise ValueError("package name must start and end with a letter or digit")
    return suffix


def _validate_patterns(patterns: list[str]) -> None:
    for pattern in patterns:
        try:
            re.compile(pattern)
        except re.error as exc:
            raise ValueError(f"invalid regex pattern {pattern!r}: {exc}") from exc


def _quote_patterns(patterns: list[str]) -> str:
    return ", ".join(repr(pattern) for pattern in patterns)


def _write_file(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists; use --force to overwrite")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _schema_blocks(module_name: str, provider_base: str, class_name: str, with_schema: bool) -> tuple[str, str, str, str, str]:
    schema_class = f"{provider_base}Schema"
    if not with_schema:
        return "", "", "", "", ""
    schema_import = f"from {module_name}.schema import {schema_class}"
    schema_init = textwrap.indent(
        'self.response_schema = kwargs.get("response_schema")\n'
        'self.structured_output = bool(kwargs.get("structured_output", False))',
        "        ",
    )
    schema_methods = textwrap.indent(
        f'''\
@classmethod
def get_schema_class(cls):
    """Return this provider's schema adapter."""
    return {schema_class}

def apply_schema(self, schema_instance):
    """Apply or clear schema configuration."""
    super().apply_schema(schema_instance)
    if schema_instance is None:
        self.response_schema = None
        self.structured_output = False
        return
    config = schema_instance.to_provider_config()
    self.response_schema = config.get("response_schema")
    self.structured_output = bool(config.get("structured_output", False))
''',
        "    ",
    )
    schema_runtime = textwrap.indent(
        'if self.response_schema and self.structured_output:\n'
        '    effective_kwargs = {**effective_kwargs, "response_schema": self.response_schema}',
        "            ",
    )
    schema_test = textwrap.indent(
        f'''\
examples = [
    data.ExampleData(
        text="Alice founded ExampleCo.",
        extractions=[
            data.Extraction(
                extraction_class="person",
                extraction_text="Alice",
                attributes={{"role": "founder"}},
            )
        ],
    )
]
schema_model = factory.create_model(
    factory.ModelConfig(model_id=model_id, provider=PROVIDER_CLASS_NAME),
    examples=examples,
    use_schema_constraints=True,
)
assert schema_model.schema is not None
assert schema_model.requires_fence_output is False
schema_outputs = list(schema_model.infer(["Alice founded ExampleCo."]))
assert schema_outputs[0][0].output == '{{"extractions": []}}'
schema_model.apply_schema(None)
assert schema_model.schema is None
print("OK: schema lifecycle")
''',
        "    ",
    )
    return schema_import, schema_init, schema_methods, schema_runtime, schema_test


def _create_files(args: argparse.Namespace) -> Path:
    provider_base = _provider_base_name(args.provider_name)
    class_name = provider_base if provider_base.endswith("LanguageModel") else f"{provider_base}LanguageModel"
    provider_display = class_name.removesuffix("LanguageModel")
    suffix = _normalize_suffix(args.package_name or _default_suffix(provider_base))
    distribution_name = f"langextract-{suffix}"
    module_name = f"langextract_{suffix.replace('-', '_')}"
    entry_point = suffix.replace("-", "_")
    env_var = re.sub(r"[^A-Z0-9]+", "_", suffix.upper()).strip("_") + "_API_KEY"
    patterns = args.patterns or [f"^{suffix}"]
    _validate_patterns(patterns)
    default_model_id = re.sub(r"^\^", "", patterns[0]) or suffix
    default_model_id = re.match(r"[A-Za-z0-9._:/-]+", default_model_id).group(0) if re.match(r"[A-Za-z0-9._:/-]+", default_model_id) else suffix

    output_root = Path(args.output_dir or ".").expanduser()
    base_dir = output_root / distribution_name
    if base_dir.exists() and not base_dir.is_dir():
        raise FileExistsError(f"target exists and is not a directory: {base_dir}")
    if base_dir.exists() and any(base_dir.iterdir()) and not args.force:
        raise FileExistsError(
            f"target directory is not empty: {base_dir}. Use --force to overwrite generated files."
        )

    schema_import, schema_init, schema_methods, schema_runtime, schema_test = _schema_blocks(
        module_name, provider_display, class_name, args.with_schema
    )

    patterns_markdown = "\n".join(f"- `{pattern}`" for pattern in patterns)
    substitutions = {
        "provider_display": provider_display,
        "class_name": class_name,
        "schema_class": f"{provider_display}Schema",
        "module_name": module_name,
        "entry_point": entry_point,
        "distribution_name": distribution_name,
        "patterns_literal": _quote_patterns(patterns),
        "patterns_list": repr(patterns),
        "patterns_markdown": patterns_markdown,
        "priority": str(args.priority),
        "env_var": env_var,
        "default_model_id": default_model_id,
        "schema_import": schema_import,
        "schema_init": schema_init,
        "schema_methods": schema_methods,
        "schema_runtime": schema_runtime,
        "schema_test": schema_test,
    }

    files: dict[Path, str] = {
        base_dir / "pyproject.toml": _PYPROJECT_TEMPLATE.substitute(substitutions),
        base_dir / "README.md": _README_TEMPLATE.substitute(substitutions),
        base_dir / "LICENSE": _LICENSE,
        base_dir / ".gitignore": _GITIGNORE,
        base_dir / _MARKER: "Generated by LangExtract provider plugin generator.\n",
        base_dir / module_name / "__init__.py": _INIT_TEMPLATE.substitute(substitutions),
        base_dir / module_name / "provider.py": _PROVIDER_TEMPLATE.substitute(substitutions),
        base_dir / "test_plugin.py": _TEST_TEMPLATE.substitute(substitutions),
    }
    if args.with_schema:
        files[base_dir / module_name / "schema.py"] = _SCHEMA_TEMPLATE.substitute(substitutions)

    for path, content in files.items():
        _write_file(path, content, force=args.force)
    return base_dir


def _install_and_test(base_dir: Path, *, install_deps: bool) -> None:
    env = os.environ.copy()
    env.setdefault("PIP_NO_INPUT", "1")
    env.setdefault("PIP_DISABLE_PIP_VERSION_CHECK", "1")
    install_cmd = [sys.executable, "-m", "pip", "install", "-e", str(base_dir)]
    if not install_deps:
        install_cmd.append("--no-deps")
    subprocess.run(install_cmd, check=True, env=env)
    subprocess.run([sys.executable, str(base_dir / "test_plugin.py")], check=True, env=env)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a self-contained LangExtract provider plugin scaffold.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """
            Examples:
              python create_provider_plugin.py MyProvider
              python create_provider_plugin.py MyProvider --with-schema --patterns '^my-model' '^myprovider/'
              python create_provider_plugin.py MyProvider --output-dir ./plugins --package-name myprovider
              python create_provider_plugin.py MyProvider --install-and-test --no-input
            """
        ),
    )
    parser.add_argument("provider_name", help="Provider display/class stem, e.g. MyProvider")
    parser.add_argument("--patterns", nargs="+", help="Regex model-ID patterns; default is based on package name")
    parser.add_argument("--package-name", help="Distribution suffix after 'langextract-', e.g. myprovider")
    parser.add_argument("--output-dir", help="Directory in which to create the plugin package; default: current directory")
    parser.add_argument("--priority", type=int, default=10, help="router.register priority; built-ins use 10")
    parser.add_argument("--with-schema", action="store_true", help="Generate a BaseSchema adapter and schema smoke checks")
    parser.add_argument("--force", action="store_true", help="Overwrite predictable generated files if the target exists")
    parser.add_argument("--install-and-test", action="store_true", help="After generation, run pip install -e and test_plugin.py")
    parser.add_argument("--install-deps", action="store_true", help="With --install-and-test, allow pip to install dependencies instead of --no-deps")
    parser.add_argument("--no-input", action="store_true", help="Accepted for scripted usage; the generator never prompts")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        base_dir = _create_files(args)
    except (FileExistsError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    print(f"Created LangExtract provider plugin scaffold: {base_dir}")
    print("Next steps:")
    print(f"  1. Edit {base_dir / 'pyproject.toml'} and provider SDK dependencies.")
    print("  2. Replace mock inference in the generated package module's provider.py with backend calls.")
    print(f"  3. Run: python {base_dir / 'test_plugin.py'}")
    print("  4. In a throwaway environment, install with: python -m pip install -e <plugin-dir>")

    if args.install_and_test:
        try:
            _install_and_test(base_dir, install_deps=args.install_deps)
        except subprocess.CalledProcessError as exc:
            print(f"ERROR: install/test command failed with exit code {exc.returncode}", file=sys.stderr)
            return exc.returncode or 1
        print("Install and non-live smoke test succeeded.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
