#!/usr/bin/env python3
"""Convert a PaddleDetection infer_cfg.yml to JSON for deployment planning."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert infer_cfg.yml to JSON.")
    parser.add_argument("infer_cfg", help="Path to infer_cfg.yml generated by PaddleDetection export.")
    parser.add_argument("--output", help="Output JSON path; default replaces .yml/.yaml with .json.")
    args = parser.parse_args()
    src = Path(args.infer_cfg)
    if not src.exists():
        parser.error(f"infer_cfg does not exist: {src}")
    if src.suffix not in {".yml", ".yaml"}:
        parser.error("expected a .yml or .yaml file")
    data = yaml.safe_load(src.read_text())
    out = Path(args.output) if args.output else src.with_suffix(".json")
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
