#!/usr/bin/env python3
"""Demonstrate LeptonAI Client PathTree naming without HTTP.

This script imports the SDK and exercises PathTree with fake callables only. It
never constructs Client(...) for a real URL, so it performs no network calls.
"""

from __future__ import annotations

from pprint import pprint
from typing import List

from leptonai.client import Client, PathTree, local


def fake_endpoint(label: str):
    def _method(**kwargs):
        return {"endpoint": label, "kwargs": kwargs}

    _method.__name__ = label
    _method.__doc__ = f"Fake endpoint {label}; generated by client_path_tree_demo.py"
    return _method


def main() -> int:
    debug_record: List[str] = []
    tree = PathTree("", debug_record)

    # Root and simple paths.
    tree._add("/", fake_endpoint("root-post"), "post")
    tree._add("/run", fake_endpoint("run-post"), "post")
    tree._add("/run", fake_endpoint("run-get"), "get")

    # Rectified path components.
    tree._add("/class", fake_endpoint("keyword-class"), "post")
    tree._add("/foo-bar/baz.qux", fake_endpoint("nested-dotted"), "get")

    # A path that is both a leaf and a prefix. The leaf is preserved as [""].
    tree._add("/branch", fake_endpoint("branch-leaf"), "post")
    tree._add("/branch/leaf", fake_endpoint("branch-child"), "get")

    # Unsupported OpenAPI-style path parameter components. These are ignored and
    # recorded in debug_record, mirroring Client's dynamic path setup behavior.
    tree._add("/items/{item_id}", fake_endpoint("item-param"), "get")
    tree._add("/{workspace}/status", fake_endpoint("workspace-param"), "get")

    print("No network calls are made by this demo.")
    print("local(8080):", local(8080))
    print("Client.local(9090):", Client.local(9090))
    print()

    print("Top-level dynamic names:")
    print(sorted(dir(tree)))
    print()

    print("All recorded paths:")
    print(tree())

    print("Call the root '/' endpoint via bracket lookup:")
    pprint(tree[""](message="root"))
    print()

    print("Duplicate GET/POST path wrapper for /run:")
    print("default method:", tree.run.default_http_method())
    print("available methods:", sorted(tree.run.methods))
    pprint(tree.run(inputs="default-call"))
    pprint(tree.run.get(q="query-call"))
    pprint(tree.run.post(inputs="post-call"))
    print()

    print("Rectified names:")
    pprint(tree.class_(value="keyword became class_"))
    pprint(tree.foo_bar.baz_qux(value="hyphen and dot became underscores"))
    print()

    print("Leaf-and-prefix path behavior for /branch and /branch/leaf:")
    print("tree.branch is a subtree listing:")
    print(tree.branch())
    print("original /branch leaf via tree.branch['']:")
    pprint(tree.branch[""](value="preserved leaf"))
    print("nested /branch/leaf:")
    pprint(tree.branch.leaf(value="nested child"))
    print()

    print("Invalid path component debug messages:")
    if debug_record:
        for message in debug_record:
            print("-", message)
    else:
        print("<none>")
    print()

    print("Missing member example:")
    try:
        tree.no_such_path
    except AttributeError as exc:
        print(type(exc).__name__ + ":", exc)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
