#!/usr/bin/env python3
"""Generate a tiny local ONNX backend-test subset.

The default behavior is deliberately bounded: it filters the ONNX backend test
corpus to small, local node or simple-model cases and writes them to a caller- 
specified output directory. It avoids real-model download workflows.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import onnx
from onnx.backend.test import cmd_tools
from onnx.backend.test.case.model import collect_testcases as collect_model_testcases
from onnx.backend.test.case.node import collect_testcases as collect_node_testcases


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a tiny local backend-test subset.")
    parser.add_argument("--output", required=True, help="Output directory for the generated subset.")
    parser.add_argument(
        "--node-op-type",
        default="Add",
        help="Node op_type to include from the backend corpus (default: Add).",
    )
    parser.add_argument(
        "--include-model-cases",
        action="store_true",
        help="Also include simple in-repo model cases in addition to the selected node cases.",
    )
    parser.add_argument("--json", action="store_true", help="Print a JSON summary instead of text.")
    return parser.parse_args()


def safe_case_name(case: Any) -> str:
    return f"{case.kind}-{case.name}"


def main() -> int:
    args = parse_args()
    outdir = Path(args.output)
    outdir.mkdir(parents=True, exist_ok=True)

    node_cases = collect_node_testcases(args.node_op_type)
    model_cases = collect_model_testcases() if args.include_model_cases else []

    # We do not call the repository's bulk generator blindly because it includes
    # real-model download cases. Instead, we emit a concise manifest and a tiny
    # corpus description that future agents can expand if needed.
    manifest = {
        "onnx_version": onnx.__version__,
        "node_op_type": args.node_op_type,
        "selected_node_cases": [safe_case_name(case) for case in node_cases[:3]],
        "selected_model_cases": [safe_case_name(case) for case in model_cases[:2]],
        "note": "Bounded helper output; use the upstream backend corpus only for explicit maintainer tasks.",
    }
    (outdir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True))
    (outdir / "README.txt").write_text(
        "This directory contains a tiny, bounded backend-test subset manifest generated by the ONNX repo skill.\n"
        "It intentionally avoids real-model downloads and large corpus material.\n"
    )

    if args.json:
        print(json.dumps(manifest, indent=2, sort_keys=True))
    else:
        print(f"Wrote backend subset manifest to {outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
