#!/usr/bin/env python3
"""Inspect Chartify style/options configuration and palette availability.

Examples:
  python check_chartify_style_config.py --print-options --check-palette Dark2
  python check_chartify_style_config.py --config-dir /tmp/chartify-config --write-sample --print-options

The script imports the installed chartify package. It does not depend on the
source repository checkout. It writes files only with --write-sample, and
Chartify YAML config should be treated as trusted local configuration only.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
from typing import Any


def _normalize_config_dir(path: str | None) -> str | None:
    if not path:
        return None
    resolved = str(Path(path).expanduser().resolve())
    if not resolved.endswith(os.sep):
        resolved += os.sep
    return resolved


def _import_chartify(config_dir: str | None):
    if config_dir:
        os.environ["CHARTIFY_CONFIG_DIR"] = config_dir
    try:
        import chartify  # type: ignore
    except ImportError as exc:  # pragma: no cover - depends on caller env
        print(
            "ERROR: could not import chartify. Install it first, for example `pip install chartify`, then rerun this helper.",
            file=sys.stderr,
        )
        print(f"Import detail: {exc}", file=sys.stderr)
        raise SystemExit(1)
    return chartify


def _write_sample_config(chartify: Any, config_dir: str) -> None:
    import yaml

    path = Path(config_dir)
    path.mkdir(parents=True, exist_ok=True)

    # options_config.yaml uses Chartify's Python-object format, so write it via
    # the package helper rather than hand-authoring unsafe YAML tags.
    chartify.options.set_option("chart.blank_labels", True)
    chartify.options.set_option("style.color_palette_categorical", "Dark2")
    chartify.options.set_option("style.color_palette_accent_default_color", "light grey")
    chartify.options._to_yaml(str(path / "options_config.yaml"))

    # style_settings_config.yaml is safe YAML and is loaded into Style.settings.
    ch = chartify.Chart(blank_labels=True)
    ch.style.settings["chart"]["figure.background_fill_color"] = "#ffffff"
    ch.style.settings["line_plot"]["line_width"] = 3
    ch.style._settings_to_yaml(str(path / "style_settings_config.yaml"))

    # color_palettes_config.yaml is safe-loaded by Chartify and expects a list of
    # [hex_colors, palette_type, name] triples.
    palette_config = [
        [["#1DB954", "#191414", "#B3B3B3"], "categorical", "Sample Brand"],
        [["#edf8fb", "#b2e2e2", "#66c2a4", "#238b45"], "sequential", "Sample Sequential"],
    ]
    with open(path / "color_palettes_config.yaml", "w", encoding="utf-8") as handle:
        yaml.safe_dump(palette_config, handle, sort_keys=False)

    # colors_config.yaml is loaded by Chartify with UnsafeLoader because tuple
    # keys are supported. This sample is trusted local config generated by this
    # helper, not arbitrary user input.
    custom_colors = {(29, 185, 84): "Spotify Green"}
    with open(path / "colors_config.yaml", "w", encoding="utf-8") as handle:
        yaml.dump(custom_colors, handle, default_flow_style=False)

    print(f"WROTE sample trusted Chartify config files under {path}")


def _print_options(chartify: Any) -> None:
    print("OPTIONS")
    for key in chartify.options._options.keys():
        print(f"{key}={chartify.options.get_option(key)!r}")


def _check_palette(chartify: Any, name: str) -> None:
    try:
        palette = chartify.color_palettes[name]
    except KeyError as exc:
        print(f"ERROR: palette {name!r} is not registered.", file=sys.stderr)
        print(
            "Known built-ins include Category20, Category10, Colorblind, Dark2, Pastel1, RdBu, RdGy, Greys, Greens, Blues, Reds, Oranges, and All colors.",
            file=sys.stderr,
        )
        print(str(exc), file=sys.stderr)
        raise SystemExit(2)
    print(f"PALETTE {name!r} OK: {palette.name!r}, type={palette.palette_type!r}, colors={len(palette.colors)}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Inspect Chartify options, palettes, and trusted YAML config behavior.")
    parser.add_argument("--config-dir", help="Trusted Chartify config directory. It is normalized to include a trailing path separator before import.")
    parser.add_argument("--write-sample", action="store_true", help="Write sample trusted Chartify config files into --config-dir.")
    parser.add_argument("--check-palette", metavar="NAME", help="Verify that a palette name is registered.")
    parser.add_argument("--print-options", action="store_true", help="Print loaded Chartify option keys and values.")
    args = parser.parse_args(argv)

    config_dir = _normalize_config_dir(args.config_dir)
    if args.write_sample and not config_dir:
        parser.error("--write-sample requires --config-dir")

    if config_dir:
        if not args.write_sample and not Path(config_dir).exists():
            print(f"ERROR: config directory does not exist: {config_dir}", file=sys.stderr)
            return 2
        print(f"Using CHARTIFY_CONFIG_DIR={config_dir!r}")
        if args.config_dir and not str(args.config_dir).endswith(os.sep):
            print("NOTE: normalized config dir with a trailing path separator for Chartify path concatenation.")

    chartify = _import_chartify(config_dir)
    print(f"chartify version: {getattr(chartify, '__version__', 'unknown')}")

    if args.write_sample:
        assert config_dir is not None
        _write_sample_config(chartify, config_dir)

    if args.print_options:
        _print_options(chartify)

    if args.check_palette:
        _check_palette(chartify, args.check_palette)

    if not (args.write_sample or args.print_options or args.check_palette):
        print("No action requested. Use --print-options, --check-palette NAME, or --write-sample.")
    print("PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
