#!/usr/bin/env python3
"""Generate an EdgeConnect YAML config from safe defaults.

The script does not import the repository package and it never launches
training. It only prints or writes YAML text.
"""

import argparse
import json
import sys
from pathlib import Path

DEFAULTS = [
    ('MODE', 1),
    ('MODEL', 1),
    ('MASK', 3),
    ('EDGE', 1),
    ('NMS', 1),
    ('SEED', 10),
    ('GPU', [0]),
    ('DEBUG', 0),
    ('VERBOSE', 0),
    ('TRAIN_FLIST', './datasets/train.flist'),
    ('VAL_FLIST', './datasets/val.flist'),
    ('TEST_FLIST', './datasets/test.flist'),
    ('TRAIN_EDGE_FLIST', './datasets/train_edges.flist'),
    ('VAL_EDGE_FLIST', './datasets/val_edges.flist'),
    ('TEST_EDGE_FLIST', './datasets/test_edges.flist'),
    ('TRAIN_MASK_FLIST', './datasets/train_masks.flist'),
    ('VAL_MASK_FLIST', './datasets/val_masks.flist'),
    ('TEST_MASK_FLIST', './datasets/test_masks.flist'),
    ('LR', 0.0001),
    ('D2G_LR', 0.1),
    ('BETA1', 0.0),
    ('BETA2', 0.9),
    ('BATCH_SIZE', 8),
    ('INPUT_SIZE', 256),
    ('SIGMA', 2),
    ('MAX_ITERS', 2000000),
    ('EDGE_THRESHOLD', 0.5),
    ('L1_LOSS_WEIGHT', 1),
    ('FM_LOSS_WEIGHT', 10),
    ('STYLE_LOSS_WEIGHT', 250),
    ('CONTENT_LOSS_WEIGHT', 0.1),
    ('INPAINT_ADV_LOSS_WEIGHT', 0.1),
    ('GAN_LOSS', 'nsgan'),
    ('GAN_POOL_SIZE', 0),
    ('SAVE_INTERVAL', 1000),
    ('SAMPLE_INTERVAL', 1000),
    ('SAMPLE_SIZE', 12),
    ('EVAL_INTERVAL', 0),
    ('LOG_INTERVAL', 10),
]


def parse_gpu(values):
    if values is None:
        return [0]

    flattened = []
    for token in values:
        token = str(token).strip()
        if not token:
            continue
        if token.lower() in {'cpu', 'none', 'off'}:
            return []
        for piece in token.split(','):
            piece = piece.strip()
            if not piece:
                continue
            flattened.append(int(piece))

    return flattened if flattened else [0]


def format_value(value):
    if value is None:
        return 'null'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return '[%s]' % ', '.join(format_value(item) for item in value)
    if isinstance(value, str):
        return json.dumps(value)

    return json.dumps(str(value))


def build_config(args):
    config = {key: value for key, value in DEFAULTS}

    if args.mode is not None:
        config['MODE'] = args.mode
    if args.model is not None:
        config['MODEL'] = args.model
    if args.mask is not None:
        config['MASK'] = args.mask
    if args.edge is not None:
        config['EDGE'] = args.edge
    if args.nms is not None:
        config['NMS'] = args.nms
    if args.seed is not None:
        config['SEED'] = args.seed

    if args.cpu:
        config['GPU'] = []
    elif args.gpu is not None:
        config['GPU'] = parse_gpu(args.gpu)

    if args.debug:
        config['DEBUG'] = 1
    if args.verbose:
        config['VERBOSE'] = 1

    for key, attr in [
        ('TRAIN_FLIST', 'train_flist'),
        ('VAL_FLIST', 'val_flist'),
        ('TEST_FLIST', 'test_flist'),
        ('TRAIN_EDGE_FLIST', 'train_edge_flist'),
        ('VAL_EDGE_FLIST', 'val_edge_flist'),
        ('TEST_EDGE_FLIST', 'test_edge_flist'),
        ('TRAIN_MASK_FLIST', 'train_mask_flist'),
        ('VAL_MASK_FLIST', 'val_mask_flist'),
        ('TEST_MASK_FLIST', 'test_mask_flist'),
    ]:
        value = getattr(args, attr)
        if value is not None:
            config[key] = value

    numeric_overrides = [
        ('LR', 'lr'),
        ('D2G_LR', 'd2g_lr'),
        ('BETA1', 'beta1'),
        ('BETA2', 'beta2'),
        ('BATCH_SIZE', 'batch_size'),
        ('INPUT_SIZE', 'input_size'),
        ('SIGMA', 'sigma'),
        ('MAX_ITERS', 'max_iters'),
        ('EDGE_THRESHOLD', 'edge_threshold'),
        ('L1_LOSS_WEIGHT', 'l1_loss_weight'),
        ('FM_LOSS_WEIGHT', 'fm_loss_weight'),
        ('STYLE_LOSS_WEIGHT', 'style_loss_weight'),
        ('CONTENT_LOSS_WEIGHT', 'content_loss_weight'),
        ('INPAINT_ADV_LOSS_WEIGHT', 'inpaint_adv_loss_weight'),
        ('GAN_POOL_SIZE', 'gan_pool_size'),
        ('SAVE_INTERVAL', 'save_interval'),
        ('SAMPLE_INTERVAL', 'sample_interval'),
        ('SAMPLE_SIZE', 'sample_size'),
        ('EVAL_INTERVAL', 'eval_interval'),
        ('LOG_INTERVAL', 'log_interval'),
    ]
    for key, attr in numeric_overrides:
        value = getattr(args, attr)
        if value is not None:
            config[key] = value

    if args.gan_loss is not None:
        config['GAN_LOSS'] = args.gan_loss

    return config


def dump_yaml(config):
    lines = [
        '# EdgeConnect config generated by make_training_config.py',
        '# Update dataset paths and stage settings before launching a run.',
    ]

    for key, _ in DEFAULTS:
        lines.append('%s: %s' % (key, format_value(config[key])))

    lines.append('')
    return '\n'.join(lines)


def build_parser():
    parser = argparse.ArgumentParser(
        description='Generate an EdgeConnect YAML config from safe defaults.'
    )
    parser.add_argument('-o', '--output', help='write YAML to this file path; omit to print to stdout')
    parser.add_argument('--mode', type=int, choices=[1, 2, 3], help='MODE value: 1 train, 2 test, 3 eval')
    parser.add_argument('--model', type=int, choices=[1, 2, 3, 4], help='MODEL value: 1 edge, 2 inpaint, 3 edge-inpaint, 4 joint')
    parser.add_argument('--mask', type=int, choices=[1, 2, 3, 4, 5], help='MASK value')
    parser.add_argument('--edge', type=int, choices=[1, 2], help='EDGE value')
    parser.add_argument('--nms', type=int, choices=[0, 1], help='NMS value')
    parser.add_argument('--seed', type=int, help='random seed')
    parser.add_argument('--cpu', action='store_true', help='force an empty GPU list for CPU-only planning')
    parser.add_argument('--gpu', nargs='*', help='GPU ids such as 0 1 or 0,1; use cpu/off/none for CPU-only output')
    parser.add_argument('--debug', action='store_true', help='set DEBUG to 1')
    parser.add_argument('--verbose', action='store_true', help='set VERBOSE to 1')

    parser.add_argument('--train-flist', dest='train_flist', help='TRAIN_FLIST path')
    parser.add_argument('--val-flist', dest='val_flist', help='VAL_FLIST path')
    parser.add_argument('--test-flist', dest='test_flist', help='TEST_FLIST path')
    parser.add_argument('--train-edge-flist', dest='train_edge_flist', help='TRAIN_EDGE_FLIST path')
    parser.add_argument('--val-edge-flist', dest='val_edge_flist', help='VAL_EDGE_FLIST path')
    parser.add_argument('--test-edge-flist', dest='test_edge_flist', help='TEST_EDGE_FLIST path')
    parser.add_argument('--train-mask-flist', dest='train_mask_flist', help='TRAIN_MASK_FLIST path')
    parser.add_argument('--val-mask-flist', dest='val_mask_flist', help='VAL_MASK_FLIST path')
    parser.add_argument('--test-mask-flist', dest='test_mask_flist', help='TEST_MASK_FLIST path')

    parser.add_argument('--lr', type=float, help='learning rate')
    parser.add_argument('--d2g-lr', dest='d2g_lr', type=float, help='discriminator to generator learning-rate ratio')
    parser.add_argument('--beta1', type=float, help='Adam beta1')
    parser.add_argument('--beta2', type=float, help='Adam beta2')
    parser.add_argument('--batch-size', dest='batch_size', type=int, help='input batch size')
    parser.add_argument('--input-size', dest='input_size', type=int, help='training image size')
    parser.add_argument('--sigma', type=int, help='Canny sigma')
    parser.add_argument('--max-iters', dest='max_iters', type=int, help='maximum training iterations')
    parser.add_argument('--edge-threshold', dest='edge_threshold', type=float, help='edge accuracy threshold')
    parser.add_argument('--l1-loss-weight', dest='l1_loss_weight', type=float, help='L1 loss weight')
    parser.add_argument('--fm-loss-weight', dest='fm_loss_weight', type=float, help='feature-matching loss weight')
    parser.add_argument('--style-loss-weight', dest='style_loss_weight', type=float, help='style loss weight')
    parser.add_argument('--content-loss-weight', dest='content_loss_weight', type=float, help='content/perceptual loss weight')
    parser.add_argument('--inpaint-adv-loss-weight', dest='inpaint_adv_loss_weight', type=float, help='adversarial loss weight for inpainting')
    parser.add_argument('--gan-loss', dest='gan_loss', choices=['nsgan', 'lsgan', 'hinge'], help='GAN loss type')
    parser.add_argument('--gan-pool-size', dest='gan_pool_size', type=int, help='fake image pool size')
    parser.add_argument('--save-interval', dest='save_interval', type=int, help='checkpoint save interval')
    parser.add_argument('--sample-interval', dest='sample_interval', type=int, help='sample save interval')
    parser.add_argument('--sample-size', dest='sample_size', type=int, help='validation sample count')
    parser.add_argument('--eval-interval', dest='eval_interval', type=int, help='internal eval interval')
    parser.add_argument('--log-interval', dest='log_interval', type=int, help='log interval')
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    config = build_config(args)
    text = dump_yaml(config)

    if args.output:
        output = Path(args.output).expanduser()
        if output.exists() and output.is_dir():
            output = output / 'config.yml'
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(text, encoding='utf-8')
        print('wrote %s' % output)
    else:
        sys.stdout.write(text)

    return 0


if __name__ == '__main__':
    sys.exit(main())
